package io.github.wiiznokes.gitnote.ui.theme

import androidx.compose.ui.graphics.Color

// Monochrome palette: no blue/purple accents.
val md_theme_light_primary = Color(0xFF1B1B1D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE5E5E7)
val md_theme_light_onPrimaryContainer = Color(0xFF151517)
val md_theme_light_secondary = Color(0xFF4F5054)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE3E3E5)
val md_theme_light_onSecondaryContainer = Color(0xFF1B1B1D)
val md_theme_light_tertiary = Color(0xFF3F4044)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE0E0E2)
val md_theme_light_onTertiaryContainer = Color(0xFF1A1A1C)
val md_theme_light_error = Color(0xFF2A2A2C)
val md_theme_light_errorContainer = Color(0xFFD8D8DA)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF151517)
val md_theme_light_background = Color(0xFFF7F7F8)
val md_theme_light_onBackground = Color(0xFF1B1B1D)
val md_theme_light_surface = Color(0xFFFAFAFB)
val md_theme_light_onSurface = Color(0xFF1B1B1D)
val md_theme_light_surfaceVariant = Color(0xFFE5E5E7)
val md_theme_light_onSurfaceVariant = Color(0xFF55565A)
val md_theme_light_outline = Color(0xFF77787C)
val md_theme_light_inverseOnSurface = Color(0xFFF4F4F5)
val md_theme_light_inverseSurface = Color(0xFF2A2A2D)
val md_theme_light_inversePrimary = Color(0xFFE6E6E8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1B1B1D)
val md_theme_light_outlineVariant = Color(0xFFC8C8CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF2F2F3)
val md_theme_dark_onPrimary = Color(0xFF202124)
val md_theme_dark_primaryContainer = Color(0xFF3A3B3F)
val md_theme_dark_onPrimaryContainer = Color(0xFFF2F2F3)
val md_theme_dark_secondary = Color(0xFFD0D0D2)
val md_theme_dark_onSecondary = Color(0xFF25262A)
val md_theme_dark_secondaryContainer = Color(0xFF343539)
val md_theme_dark_onSecondaryContainer = Color(0xFFE6E6E8)
val md_theme_dark_tertiary = Color(0xFFE0E0E2)
val md_theme_dark_onTertiary = Color(0xFF25262A)
val md_theme_dark_tertiaryContainer = Color(0xFF3B3C40)
val md_theme_dark_onTertiaryContainer = Color(0xFFF0F0F1)
val md_theme_dark_error = Color(0xFFE8E8EA)
val md_theme_dark_errorContainer = Color(0xFF3B3C40)
val md_theme_dark_onError = Color(0xFF202124)
val md_theme_dark_onErrorContainer = Color(0xFFF1F1F2)

// Soft gray surfaces for reading; monochrome accents only.
val md_theme_dark_background = Color(0xFF202124)
val md_theme_dark_onBackground = Color(0xFFE7E7E9)
val md_theme_dark_surface = Color(0xFF25262A)
val md_theme_dark_onSurface = Color(0xFFE7E7E9)
val md_theme_dark_surfaceVariant = Color(0xFF333438)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC0C4)
val md_theme_dark_outline = Color(0xFF77787D)
val md_theme_dark_inverseOnSurface = Color(0xFF202124)
val md_theme_dark_inverseSurface = Color(0xFFE7E7E9)
val md_theme_dark_inversePrimary = Color(0xFF2B2C30)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE7E7E9)
val md_theme_dark_outlineVariant = Color(0xFF45464B)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF808084)
